<a href="https://colab.research.google.com/github/sanjanapatilvv5/NNDL-Lab/blob/main/NNDL_EXP_2_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#EXP---2
# Install numpy (if not already installed)
!pip install numpy

# Import
import numpy as np

# -----------------------------
# 0D Tensor (Scalar)
# -----------------------------
x = np.array(8)
print("Scalar:", x)
print("Dimensions:", x.ndim)
print()

# -----------------------------
# 1D Tensor (Vector)
# -----------------------------
vec = np.array([10, 20, 30, 40, 50])
print("Vector:", vec)

# Loop through elements
for element in vec:
    print("Element:", element)

print()

# Vector with index
x = np.array([5, 10, 15])
for i, val in enumerate(x):
    print(f"Index {i}: {val}")

print("Dimensions:", x.ndim)
print("Shape:", x.shape)
print()

# -----------------------------
# 2D Tensor (Matrix)
# -----------------------------
mat = np.array([
    [3, 4, 7],
    [6, 8, 9],
    [10, 11, 12]
])

print("Matrix:\n", mat)
print("Dimensions:", mat.ndim)
print("Shape:", mat.shape)

Scalar: 8
Dimensions: 0

Vector: [10 20 30 40 50]
Element: 10
Element: 20
Element: 30
Element: 40
Element: 50

Index 0: 5
Index 1: 10
Index 2: 15
Dimensions: 1
Shape: (3,)

Matrix:
 [[ 3  4  7]
 [ 6  8  9]
 [10 11 12]]
Dimensions: 2
Shape: (3, 3)


In [2]:
#EXP-3.............
# Install numpy
!pip install numpy

# Import numpy
import numpy as np

# Define vectors
v1 = np.array([10, 20, 30])
v2 = np.array([2, 4, 5])

# Vector operations
addition = v1 + v2
subtraction = v1 - v2
multiplication = v1 * v2
division = v1 / v2

# Print results
print("Vector 1:", v1)
print("Vector 2:", v2)

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

Vector 1: [10 20 30]
Vector 2: [2 4 5]
Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]
